
@startuml findGreatestCommonDivisor
title findGreatestCommonDivisor
start
: Read a, b;
repeat:(b  not equal to  0 )    
     : temp assign value    b ; 
    :b assign value  a modulo  b   ; 
    : a assign value  temp ; 
repeat while(true)
: return  a ; 
stop
@enduml