
@startuml findGreatestCommonDivisor
title findLeastCommonMultiple
start
: Read a, b;
: count  assign value   2 ; 
:  leastCommonMul assign value  1;    
repeat: while (a not equal to 1 and  b not equal to 1) 
if ( primeNumberCheckAlgorithm(count) ) then ( yes)
    repeat :  (a modulo  count equal to  0  or b modulo  count  equal to  0)    
    if ( a modulo  count  equal to   0 ) 
      :a assign value  Math.floor(a divided by count);
    endif  
    if(b modulo   count  equal to  0  ) 
      :b assign value  Math.floor(b divided by count);
    endif
    :leastCommonMul *= count; 
    repeat  while (true)   

endif  
:count increment   ; 
repeat while (true)
stop
@enduml