
@startuml findMaxIndex
title findMaxIndex
start
: Read array  ;
: maxIndex assign value     0 ;  
repeat:(for (let count assign value  1; count smaller than  array.length; count increment) )    
      if( array[count] larger than array[maxIndex]) then (yes)
        : maxIndex assign value  count; 
      endif 
repeat while(true)
:  return maxIndex; 
stop
@enduml