
@startuml findMinIndex
title findMinIndex
start
: Read array  ;
: minIndex assign value     0 ;  
repeat:(for (let count assign value  1; count smaller than  array.length; count increment) )    
      if( array[count] smaller than   array[minIndex]) then (yes)
        : minIndex assign value  count; 
      endif 
repeat while(true)
:  return minIndex; 
stop
@enduml