
@startuml findSum
title findSum
start
: Read array  ;
: sumArr assign value  0; 
repeat:(for (let count assign value  0; count smaller than  array.length; count increment)  )    
    :sumArr increment by  array[count]; 
repeat while(true)
:  return sumArr; 
stop
@enduml