
@startuml findMaxIn2DArray
title findMaxIn2DArray
start
: Read arr2D  ;
: max assign value  arr2D[0][0];
repeat:for (let countRow assign value  0; countRow smaller than  arr2D.length; countRow increment)   
    repeat:for (let countColumn assign value  0; countColumn smaller than  arr2D[0].length; countColumn increment)     
    if (arr2D[countRow][countColumn] larger than max) then (yes ) 
        :max assign value  arr2D[countRow][countColumn];
    endif 
repeat while(true)
repeat while(true)
:  return max; 
stop
@enduml