
@startuml findMaxIn2DArray
title findMaxIn2DArray
start
: user input arr2D  ;
: max = arr2D[0][0];
repeat:for (let i = 0; i < arr2D.length; i++)   
    repeat:for (let j = 0; j < arr2D[0].length; j++)     
    if (arr2D[i][j] > max) then (yes ) 
        :max = arr2D[i][j];
    endif 
repeat while(true)
repeat while(true)
:  return max; 
stop
@enduml