
@startuml findMinIn2DArray
title findMinIn2DArray
start
: Read arr2D  ;
: min assign value  arr2D[0][0];
repeat:for (let countRow assign value  0; countRow smaller than  arr2D.length; countRow increment)   
    repeat:for (let countColumn assign value  0; countColumn smaller than  arr2D[0].length; countColumn increment)     
    if (arr2D[countRow][countColumn] larger than min) then (yes ) 
        :min assign value  arr2D[countRow][countColumn];
    endif 
repeat while(true)
repeat while(true)
:  return min; 
stop
@endumld