
@startuml  sumRowOrColumn
title  sumRowOrColumn
start
: Read arr2D, k, isRow assign value  true  ;
:  sum assign value   0;
if (isRow) then (yes)  
repeat:  for (let countColumn assign value  0; countColumn smaller than  arr2D[0].length; countColumn increment)
 :sum increment by  arr2D[k][countColumn]; 
repeat  while(true )
else 
repeat:  for (let countRow assign value  0; countColumn smaller than  arr2D[0].length; countColumn increment)
: sum increment by  arr2D[countRow][k]; 
repeat  while(true )
endif 
 :return sum;
stop

@enduml