
@startuml  sumRowOrColumn
title  sumRowOrColumn
start
: user input arr2D, k, isRow = true  ;
:  sum =  0;
if (isRow) then (yes)  
repeat:  for (let j = 0; j < arr2D[0].length; j++)
 :sum += arr2D[k][j]; 
repeat  while(true )
else 
repeat:  for (let i = 0; j < arr2D[0].length; j++)
: sum += arr2D[i][k]; 
repeat  while(true )
endif 
 :return sum;
stop

@enduml