@startuml 
    title sumOfFirstNNumbers
    start
    :user input n ;
    : sum =  0; 
    : i = 0 ; 
    repeat: i++ ;
    : sum  =  sum  + i  ;
    repeat  while (i <= n) is(yes)
    -> no ; 
    :console.log(sum);
    stop
@enduml
