@startuml 
    title sumOfFirstNNumbers
    start
    :Read number ;
    : sum assign value   0; 
    : count assign value  0 ; 
    repeat: count increment ;
    :   sum  add count  assign value to sum ;
    repeat  while (count  smaller or equal to number) is(yes)
    -> no ; 
    :show the output of(sum);
    stop
@enduml
