@startuml 
title  sumOfDivisors
    start
    :Read number ;
    : sum assign value   0; 
    : count assign value  0 ; 
    repeat: count increment ;
    if(number  modulo  count equal to  0) then (yes)
        : sum  assign value   sum  add count  ;
    else (no) 
    endif
    repeat  while (count  smaller or equal to number) is(yes) 
    -> no ; 
    :show the output of(sum);
    stop
@enduml
