@startuml 
    title   sumOfDigits 
    start
    :Read  number;
    : sum assign value   0; 
    repeat:     number modulo  10 assign value  to lastDigit;
    :  Math.floor (number  divided by 10)  assign value to number ; 
    :   sum  add lastDigit  assign value to sum ;
    repeat  while (number larger than 0 ) is(yes)
    -> no ; 
    :show the output of(sum);
    stop
@enduml
