@startuml 
    title   SumOfDigits 
    start
    :Read  number;
    : sum assign value   0; 
    repeat: lastDigit  assign value   number modulo  10;
    : number  assign value  Math.floor (number  divided by 10)  ; 
    : sum  assign value   sum  add lastDigit  ;
    repeat  while (number larger than 0 ) is(yes)
    -> no ; 
    :show the output of(sum);
    stop
@enduml
