@startuml   
    title  findMaxDigit
    start
    : Read number;
    : currentDigit assign value  0  ; 
    : max  assign value   0  ;  
    repeat: currentDigit  assign value   number modulo  10;
    : number  assign value  Math.floor (number  divided by 10)  ; 
    if(max  smaller than  currentDigit ) then (yes)
        : max assign value   currentDigit  ; 
    else (no) 
    endif 
    repeat  while (number > 0 ) is(yes)
    -> no ; 
    :show user result output;
    stop
@enduml
