@startuml 
    title findSecondMaxInArray
    start
    : Read array;
    : max assign value  array[0] ; 
    : count  assign value   0  ; 
    : secondMax assign value  array[0] ;  
    repeat 
    if(array[count] larger than  max  ) then (yes)
        : secondMax assign value   max  ;
        : max assign value   array[count]  ;  
    else (no) 
    endif 
    : count increment   ;
    repeat  while ( count smaller than  array.length ) is(yes)
    -> no ; 
    :show the output of(secondMax);
    stop
@enduml
