@startuml 
title findSecondMinInArray 
    start
    : Read array;
    : min assign value  array[count]  ; 
    : count  assign value   1 ; 
    : secondmin assign value  array[count] ;  
    repeat 
    if(array[count] smaller than   min  ) then (yes)
        : secondmin  assign value   min  ; 
        : min assign value   array[count]  ;  
    else (no) 
    endif 
    : count increment   ;
    repeat  while ( count smaller than  array.length ) is(yes)
    -> no ; 
    :show the output of(secondmin);
    stop
@enduml
