@startuml
start
title  findPrimesInArray 
: Read array;
: countRow assign value  0;
repeat
 :  isPrime assign value  true  ; 
  : countColumn assign value  2;
  repeat
    if (array[countRow] modulo  countColumn equal to  0) then (yes)
      : break;
    else (no)
    endif
    : countColumn increment;
  repeat while (countColumn  smaller or equal to Math.floor(array[countRow] divided by 2)) is (yes)
  if (isPrime  and   array[countRow] larger than 1) then (yes)
    : show the output of(array[countRow]);
  else (no)
  endif
  : countRow increment;
repeat while (countRow smaller than  array.length) is (yes)
stop
@enduml