@startuml
    title primeNumberCheckAlgorithm
    start
    : Read number;  
    if(number  smaller or equal to1) then (yes) 
    : return false  ;
    endif 
    : count assign value  2  ;  
    repeat 
    if(number  modulo  count  equal to  0  ) then (yes)
        : return false ;  
    else (no) 
    endif 
    : count increment   ;
    repeat  while ( count  smaller or equal to Math.floor(numberdivided by2) ) is(yes)
    -> no ; 
    : return true;
    stop
@enduml
