@startuml
    title primeNumberCheckAlgorithm
    start
    : user input n;  
    if(n <=1) then (yes) 
    : return false  ;
    endif 
    : i = 2  ;  
    repeat 
    if(n  % i  == 0  ) then (yes)
        : return false ;  
    else (no) 
    endif 
    : i++   ;
    repeat  while ( i <= Math.floor(n/2) ) is(yes)
    -> no ; 
    : return true;
    stop
@enduml
