@startuml 
    title CheckPerfectNumber
    start
    : Read number; 
    : count assign value  1 ;  
    : perfectNumber  assign value  0  ;  
    repeat 
    : perfectNumber  assign value   (Math.pow(2, count   decrease by  1) * (Math.pow(2,count)  decrease by  1))   ; 
    if(perfectNumber equal to  number) then (yes)
    : return true ; 
    else (no)  
    endif  
    : count increment   ;
    repeat  while ( perfectNumber smaller than  number ) is(yes)
    -> no ; 
    : return false;
    stop
@enduml
