@startuml CheckPerfectSquare
    title CheckPerfectSquare
    start
    : Read number; 
    if (Number.isInteger(Math.sqrt(number))) then (yes)
        : return true; 
    endif
     : return false; 
@enduml