@startuml
title printPrimesUpToN
start
: Read number;
: count assign value  1;
repeat
  : countColumn assign value  2;
  repeat
    if (count modulo  countColumn equal to  0) then (yes)
      : break;
    else (no)
    endif
    : countColumn increment;
  repeat while (countColumn  smaller or equal to Math.floor(count divided by 2)) is (yes)
  if (countColumn larger than Math.floor(count divided by 2)) then (yes)
    : show the output of(count);
  else (no)
  endif
  : count increment;
repeat while (count  smaller or equal to number) is (yes)
stop
@enduml