
@startuml.
title reverseString
start
: Read stringArray;
: arrayString assign value   stringArray.split('') ;
:    arrayString.length  decrease by  1  assign value to count;
: reverseString assign value "" ; 
repeat
 : reverseString  add assign value   arrayString[count]   ;  
  :count decrease  ; 
repeat while (count larger than 0 ) is (yes)
: return  reverseString ; 
stop
@enduml