
@startuml.
title reverseString
start
: Read stringArray;
: arrStr assign value   stringArray.split('') ;
: count assign value  arrStr.length  decrease by  1 ;
: reverseStr assign value  '' ; 
repeat
 : reverseStr  add assign value   arrStr[count]   ;  
  :count decrease  ; 
repeat while (count larger than 0 ) is (yes)
: return  reverseStr ; 
stop
@enduml