@startuml RemoveWhitespaceFromString
title removeWhitespaceFromString
start
: Read stringArray;
:arrayString assign value  stringArray.split("");
: count assign value  0;
: noSpaceString assign value  ""; 
repeat  
  if (arrayString[count] not equal to "") then (yes)
    : noSpaceString increment by  arrayString[count];  
  endif 
  : count increment;
repeat while (count smaller than  arrayString.length) is (yes)
: return noSpaceString; 
stop
@enduml