@startuml RemoveWhitespaceFromString
title RemoveWhitespaceFromString
start
: Read stringArray;
:arrStr assign value  stringArray.split("");
: count assign value  0;
: noSpaceStr assign value  ''; 
repeat  
  if (arrStr[count] not equal to ' ') then (yes)
    : noSpaceStr increment by  arrStr[count];  
  endif 
  : count increment;
repeat while (count smaller than  arrStr.length) is (yes)
: return noSpaceStr; 
stop
@enduml