

@startuml.
title checkPalindromeString
start
: Read stringArray;

: reverseStr assign value  reverseString(stringArray) ; 
if ( reverseStr  equal to   stringArray)  then (yes)
: return true ;  
endif
:  return false  ; 
stop
@enduml