

@startuml.
title checkPalindromeString
start
: Read stringArray;

: reverseString assign value  reverseString(stringArray) ; 
if ( reverseString  equal to   stringArray)  then (yes)
: return true ;  
endif
:  return false  ; 
stop
@enduml