@startuml 
title findLongestPalindromicSubstring
start
: Read stringArray;
: longestPalindromic assign value  '';
: countRow assign value  0;
repeat
  : countColumn assign value  countRow;
  : substring assign value  '';
  repeat
    : substring assign value  stringArray.substring(countRow, countColumn add  1);
    if((checkPalindromeString(substring) and  substring.length) larger than longestPalindromic.length) then (yes)
        : longestPalindromic assign value  substring;
    endif 
    : countColumn increment;
  repeat while (countColumn smaller than  stringArray.length) is (yes)
  : countRow increment;
repeat while (countRow smaller than  stringArray.length) is (yes)
: return longestPalindromic; 
stop
@enduml