@startuml
title bubbleSort
start
: user input arr;
: i = 0;
repeat
  : j = i;
  repeat
    if (arr[j] > arr[j + 1]) then (yes)
      : temp = arr[j];
      : arr[j] = arr[j + 1];
      : arr[j + 1] = temp;
    endif
    : j++;
  repeat while (j < arr.length - i - 1) is (yes)
  : i++;
repeat while (i < arr.length - 1) is (yes)
: return arr;
stop
@enduml