@startuml
title bubbleSort
start
: Read array;
: countRow assign value  0;
repeat
  : countColumn assign value  countRow;
  repeat
    if (array[countColumn] larger than array[countColumn add  1]) then (yes)
      : temp assign value  array[countColumn];
      : array[countColumn] assign value  array[countColumn add  1];
      : array[countColumn add  1] assign value  temp;
    endif
    : countColumn increment;
  repeat while (countColumn smaller than  (array.length  decrease by  countRow  decrease by  1)) is (yes)
  : countRow increment;
repeat while (countRow smaller than  array.length  decrease by  1) is (yes)
: return array;
stop
@enduml