@startuml calculateAndPrintFactorial
title calculateAndPrintFactorial
start
: Read number;
: count assign value  1;
: nFactorial assign value  1; 
repeat
:  nFactorial multiply by  count assign value to nFactorial; 
: count increment;
repeat while (count  smaller or equal to number)
: show the output of(nFactorial);
stop
@enduml