@startuml calculateAndPrintSumOfDigits
title calculateAndPrintSumOfDigits
start
: Read number;
: nSum assign value  0;
repeat 
  :   nSum add  (number modulo  10) assign value to nSum;
  :  Math.floor(number divided by 10) assign value to number;
repeat while (number larger than 0)
: show the output of(nSum);
stop
@enduml