@startuml calculateAndPrintSumOfDigits
title calculateAndPrintSumOfDigits
start
: user input n;
: nSum = 0;
repeat 
  : nSum = nSum + (n % 10);
  : n = Math.floor(n / 10);
repeat while (n > 0)
: console.log(nSum);
stop
@enduml