@startuml calculateAndPrintSumOfDigits
title calculateAndPrintSumOfDigits
start
: Read number;
: nSum assign value  0;
repeat 
  : nSum assign value  nSum add  (number modulo  10);
  : number assign value  Math.floor(number divided by 10);
repeat while (number larger than 0)
: show the output of(nSum);
stop
@enduml