@startuml
title printFirstnFibonacciNumbers.
start
: Read number;
: countRow assign value  0 ;
: countColumn assign value   1 ;
repeat
: temp  assign value   countRow add  countColumn   ;
: show the output of(countRow )  ;
: countRow  assign value   countColumn  ; 
: countColumn assign value  temp  ; 
repeat while ( countRow  smaller or equal to number )
stop
@enduml