@startuml countVowelsInString
title countVowelsInString
start
: Read stringArray;
: stringArray assign value  stringArray.toLowerCase();
: arrayString assign value  stringArray.split();
: vowels assign value  ['a', 'e', 'count', 'o', 'u'];
: numberOfVowels assign value  0;
: count assign value  0;
repeat
if (vowels.includes(arrayString[count])) then (yes)
    : numberOfVowels increment;
endif
: count increment;
repeat while (count smaller than  arrayString.length)
: show the output of(numberOfVowels);
stop
@enduml