@startuml countCharOccurrences
title countCharOccurrences
start
: Read stringArray;
: Read charToFind;
: stringArray assign value  stringArray.toLowerCase();
: arrayString assign value   stringArray.split('') ;
: numberOfRepeat assign value  0;
: count assign value  0;
repeat 
  if (arrayString[count] equal to  charToFind) then (yes)
    : numberOfRepeat increment;
  endif
  : count increment;
repeat while (count smaller than  arrayString.length)
: show the output of(numberOfRepeat);
stop
@enduml