@startuml findMostFrequentChars
title findMostFrequentChars
start
: Read stringArray;
: stringArray assign value  stringArray.toLowerCase();
: arrStr assign value   stringArray.split("");
: MaxCount assign value  0; 
: charDict assign value  {};
: result assign value  [];
: count assign value  0;
repeat
if (arrStr[count] in charDict) then (yes)
    : charDict[arrStr[count]] increment by  1;
else (no)
    : charDict[arrStr[count]] assign value  1;
endif
: count increment;
repeat while (count smaller than  arrStr.length)

repeat : (key in charDict.keys())
if (charDict[key] larger than MaxCount) then (yes)
    : MaxCount assign value  charDict[key];
endif
repeat while (true)

repeat : (key in charDict.keys())
if (charDict[key] equal to  MaxCount) then (yes)
    : result.append(key);
endif
repeat while (true)

: show the output of(result);
stop
@enduml