@startuml 
title findLongestIncreasingAndDecreasingSubsequence
start
: Read stringArray;
: maxIncreasingSub assign value  '' ;
: maxDecreasingSub assign value  '' ;
repeat : for (let countRow assign value  0; countRow smaller than  stringArray.length; countRow increment)
  : increasingSub assign value  stringArray[countRow];
  : decreasingSub assign value  stringArray[countRow];

  repeat : for (let countColumn assign value  countRow; countColumn smaller than  stringArray.length  decrease by  1; countColumn increment)
    if (stringArray[countColumn] smaller than  stringArray[countColumn add  1]) then (yes)
      : increasingSub increment by  stringArray[countColumn add  1];
    else (no)
      if (maxIncreasingSub.length smaller than  increasingSub.length) then (yes)
        : maxIncreasingSub assign value  increasingSub;
      endif
      : increasingSub assign value  stringArray[countColumn add  1];
    endif
  repeat while (true)
   if (maxIncreasingSub.length smaller than  increasingSub.length) then (yes)
      : maxIncreasingSub assign value  increasingSub;
    endif
  repeat : for (let countColumn assign value  countRow; countColumn smaller than  stringArray.length  decrease by  1; countColumn increment)
    if (stringArray[j] larger than stringArray[j add  1]) then (yes)
      : decreasingSub increment by  stringArray[j add  1];
    else (no)
      if (maxDecreasingSub.length smaller than  decreasingSub.length) then (yes)
        :           maxDecreasingSub assign value  decreasingSub;
      endif
      :  decreasingSub assign value  stringArray[j add  1];
    endif
  repeat while (true)
   if (maxDecreasingSub.length smaller than  decreasingSub.length) then (yes)
      : maxDecreasingSub assign value  decreasingSub;
    endif
repeat while (true)
@enduml