@startuml findMostFrequentChars
title sortString
start
: Read stringArray;
:  array assign value   stringArray.split('')  ; 
repeat: for (let count assign value  1; count smaller than  array.length; count increment)   ; 
: temp  assign value   array[count]  ; 
: countColumn assign value   count  ; 
repeat:(countColumn larger than 0 and  temp smaller than  array[countColumn  decrease by  1])    
:array[countColumn] assign value  array[countColumn  decrease by  1];
      :countColumn decrease;
repeat while(true)
repeat while (true)
:return  array.join(''); 
stop
@enduml